### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by NabilHY** [NabilHY/space-hub#25]
https://github.com/NabilHY/space-hub/projects/2?query=is%3Aopen+sort%3Aupdated-desc
Hello, Hope you have a good day, this project has two members including myself.

**Comment by Gambit142** [comment]
Hi @NabilHY @ppmarq1 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

#### Great work setting up the Kanban board. You can start executing the project. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
